@startuml

title __D2RQ_SDB's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace d2rq_sdb {
        class de.fuberlin.wiwiss.d2rq.d2rq_sdb.AllTests {
            {static} + main()
            {static} + suite()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace d2rq_sdb {
        abstract class de.fuberlin.wiwiss.d2rq.d2rq_sdb.LoadDataTest {
            {static} # CURR_DIR : String
            # hsqlDataModel : Model
            # sdbDataModel : Model
            {static} - CONFIG_DIR : String
            {static} - DATA_DIR : String
            {static} - FILENAME_SQL_DATA : String
            {static} - FILENAME_TTL_DATA : String
            {static} - HSQL_DRIVER_NAME : String
            {static} - HSQL_PASS : String
            {static} - HSQL_URL : String
            {static} - HSQL_USER : String
            {static} - MAPPING_FILE_HSQL : String
            {static} - SDB_PASS : String
            {static} - SDB_URL : String
            {static} - SDB_USER : String
            {static} - loadHsqlData : boolean
            {static} - loadSDBData : boolean
            + LoadDataTest()
            - convertStreamToString()
            - createHsqlDatabase()
            - createSemanticDatabase()
            - initDatabases()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace d2rq_sdb {
        class de.fuberlin.wiwiss.d2rq.d2rq_sdb.SdbSqlEqualityTest {
            {static} - QUERY_DIR : String
            {static} - QUERY_FILE_SUFFIX : String
            - excludedQueriesFileNames : String[]
            + SdbSqlEqualityTest()
            + testSdbSqlEquality()
            - createQuery()
            - excludeFile()
            - loadAllQueries()
            - readRecursiveAndCreateQuery()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace d2rq_sdb {
        class de.fuberlin.wiwiss.d2rq.d2rq_sdb.SdbSqlEqualityTest.StatementsComparator {
            + compare()
        }
      }
    }
  }
  

  de.fuberlin.wiwiss.d2rq.d2rq_sdb.SdbSqlEqualityTest +-down- de.fuberlin.wiwiss.d2rq.d2rq_sdb.SdbSqlEqualityTest.StatementsComparator
  de.fuberlin.wiwiss.d2rq.d2rq_sdb.SdbSqlEqualityTest.StatementsComparator .up.|> Comparator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
