@startuml

title __TOOLS's Class Diagram__\n

  namespace  {
    namespace utoweka {
      namespace tools {
        class autoweka.tools.DatasetStats {
            {static} ~ log : Logger
            {static} + main()
        }
      }
    }
  }
  

  namespace  {
    namespace utoweka {
      namespace tools {
        class autoweka.tools.ExperimentRunner {
            {static} ~ log : Logger
            {static} + main()
        }
      }
    }
  }
  

  namespace  {
    namespace utoweka {
      namespace tools {
        class autoweka.tools.GetBestFromTrajectoryGroup {
            + attributeEvalArgs : String
            + attributeEvalClass : String
            + attributeSearchArgs : String
            + attributeSearchClass : String
            + classifierArgs : String
            + classifierClass : String
            + errorEstimate : float
            + experiment : Experiment
            + numEval : int
            + numMemOut : int
            + numTimeOut : int
            + numTrajectories : int
            + rawArgs : String
            + seed : String
            {static} ~ log : Logger
            + GetBestFromTrajectoryGroup()
            + GetBestFromTrajectoryGroup()
            {static} + main()
        }
      }
    }
  }
  

  namespace  {
    namespace utoweka {
      namespace tools {
        class autoweka.tools.ParamFilterer {
            {static} ~ log : Logger
            {static} + main()
        }
      }
    }
  }
  

  namespace  {
    namespace utoweka {
      namespace tools {
        class autoweka.tools.TrainedModelPredictionMaker {
            + eval : Evaluation
            {static} ~ log : Logger
            + TrainedModelPredictionMaker()
            {static} + main()
        }
      }
    }
  }
  

  namespace  {
    namespace utoweka {
      namespace tools {
        class autoweka.tools.TrajectoryTruncator {
            {static} ~ log : Logger
            {static} + clipTrajectoryGroupFile()
            {static} + main()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
