@startuml

title __D2RQ's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      class de.fuberlin.wiwiss.d2rq.AllTests {
          {static} + suite()
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      class de.fuberlin.wiwiss.d2rq.D2RQTestSuite {
          {static} + DIRECTORY : String
          {static} + DIRECTORY_URL : String
          {static} + ISWC_MAP : String
          {static} + loadTurtle()
          {static} + main()
          {static} + suite()
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      class de.fuberlin.wiwiss.d2rq.DBConnectionTest {
          - cdb : ConnectedDB
          - complexQuery : String
          - databases : Collection<Database>
          - firstDatabase : Database
          - mapModel : Model
          - mediumQuery : String
          - simplestQuery : String
          + manuallyConfiguredConnection()
          + testConnections()
          + testDistinct()
          + testLongComplexSQLQuery()
          + testMedium()
          + xtestManuallyConfiguredConnection()
          # setUp()
          # tearDown()
          {static} - performQuery()
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      class de.fuberlin.wiwiss.d2rq.JenaAPITest {
          + testCopyPrefixesFromMapModelToD2RQGraph()
          + testCopyPrefixesFromMapModelToD2RQModel()
          + testDontCopyD2RQPrefixFromMapModel()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
