@startuml

title __META's Class Diagram__\n

  namespace  {
    namespace eka.classifiers.meta {
      class weka.classifiers.meta.AutoWEKAClassifier {
          {static} + configurationHashSetPath : String
          {static} + configurationInfoDirPath : String
          {static} + configurationRankingPath : String
          + totalTried : int
          # DEFAULT_PARALLEL_RUNS : int
          # as : AttributeSelection
          # attributeEvalArgs : String[]
          # attributeEvalClass : String
          # attributeSearchArgs : String[]
          # attributeSearchClass : String
          # bestConfigsCollection : ConfigurationCollection
          # classifier : Classifier
          # classifierArgs : String[]
          # classifierClass : String
          # estimatedMetricValue : double
          # estimatedMetricValues : double[]
          # eval : Evaluation
          {static} # expName : String
          # extraArgs : String
          # finalTrainTime : double
          # memLimit : int
          {static} # msExperimentPaths : String[]
          # nBestConfigs : int
          # parallelRuns : int
          # resamplingArgs : String
          # seed : int
          # timeLimit : int
          {static} ~ DEFAULT_EXTRA_ARGS : String
          {static} ~ DEFAULT_MEM_LIMIT : int
          {static} ~ DEFAULT_METRIC : Metric
          {static} ~ DEFAULT_N_BEST : int
          {static} ~ DEFAULT_RESAMPLING : Resampling
          {static} ~ DEFAULT_RESAMPLING_ARGS : String
          {static} ~ DEFAULT_TIME_LIMIT : int
          ~ log : Logger
          {static} ~ metricsToMax : Metric[]
          {static} ~ resamplingArgsMap : Map<Resampling, String>
          {static} ~ serialVersionUID : long
          - wLog : Logger
          + AutoWEKAClassifier()
          + buildClassifier()
          + classifyInstance()
          + distributionForInstance()
          + enumerateMeasures()
          + getCapabilities()
          + getMeasure()
          + getMemLimit()
          + getMetric()
          + getOptions()
          + getParallelRuns()
          + getSeed()
          + getTechnicalInformation()
          + getTimeLimit()
          + getnBestConfigs()
          + globalInfo()
          + listOptions()
          {static} + main()
          + measureEstimatedMetricValue()
          + memLimitTipText()
          + metricTipText()
          + nBestConfigsTipText()
          + parallelRunsTipText()
          + seedTipText()
          + setLog()
          + setMemLimit()
          + setMetric()
          + setOptions()
          + setParallelRuns()
          + setSeed()
          + setTimeLimit()
          + setnBestConfigs()
          + timeLimitTipText()
          + toString()
      }
    }
  }
  

  namespace  {
    namespace eka.classifiers.meta {
      enum Metric {
        areaAboveROC
        areaUnderROC
        avgCost
        correct
        correlationCoefficient
        errorRate
        fMeasure
        falseNegativeRate
        falsePositiveRate
        incorrect
        kBInformation
        kBMeanInformation
        kBRelativeInformation
        kappa
        meanAbsoluteError
        pctCorrect
        pctIncorrect
        precision
        relativeAbsoluteError
        rootMeanSquaredError
        rootRelativeSquaredError
        weightedAreaUnderROC
        weightedFMeasure
        weightedFalseNegativeRate
        weightedFalsePositiveRate
        weightedPrecision
        weightedRecall
        weightedTrueNegativeRate
        weightedTruePositiveRate
      }
    }
  }
  

  namespace  {
    namespace eka.classifiers.meta {
      enum Resampling {
        CrossValidation
        MultiLevel
        RandomSubSampling
        TerminationHoldout
      }
    }
  }
  

  weka.classifiers.meta.AutoWEKAClassifier .up.|> AdditionalMeasureProducer
  weka.classifiers.meta.AutoWEKAClassifier o-- weka.classifiers.meta.AutoWEKAClassifier.Metric : metric
  weka.classifiers.meta.AutoWEKAClassifier o-- weka.classifiers.meta.AutoWEKAClassifier.Resampling : resampling
  weka.classifiers.meta.AutoWEKAClassifier +-down- weka.classifiers.meta.AutoWEKAClassifier.Metric
  weka.classifiers.meta.AutoWEKAClassifier +-down- weka.classifiers.meta.AutoWEKAClassifier.Resampling


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
