@startuml

title __JENA's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace jena {
        class de.fuberlin.wiwiss.d2rq.jena.CachingGraphD2RQ {
            - queryCache : Map<TripleMatch, List<Triple>>
            + CachingGraphD2RQ()
            + clearCache()
            + graphBaseFind()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace jena {
        class de.fuberlin.wiwiss.d2rq.jena.D2RQQueryHandler {
            - dataset : DatasetGraph
            - indexes : Map<Node, Integer>
            - variables : Node[]
            + D2RQQueryHandler()
            + prepareBindings()
            + prepareTree()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace jena {
        class de.fuberlin.wiwiss.d2rq.jena.D2RQQueryHandler.BindingToDomain {
            + map1()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace jena {
        class de.fuberlin.wiwiss.d2rq.jena.GraphD2RQ {
            {static} - capabilities : Capabilities
            {static} - log : Log
            - mapping : Mapping
            + GraphD2RQ()
            + close()
            + getCapabilities()
            + getMapping()
            + graphBaseFind()
            + queryHandler()
            # checkOpen()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace jena {
        class de.fuberlin.wiwiss.d2rq.jena.ModelD2RQ {
            + ModelD2RQ()
            + ModelD2RQ()
            + ModelD2RQ()
            + ModelD2RQ()
            + getGraph()
        }
      }
    }
  }
  

  de.fuberlin.wiwiss.d2rq.jena.D2RQQueryHandler +-down- de.fuberlin.wiwiss.d2rq.jena.D2RQQueryHandler.BindingToDomain
  de.fuberlin.wiwiss.d2rq.jena.D2RQQueryHandler.BindingToDomain .up.|> Map1
  de.fuberlin.wiwiss.d2rq.jena.GraphD2RQ .up.|> Graph
  de.fuberlin.wiwiss.d2rq.jena.ModelD2RQ .up.|> Model


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
