@startuml

title __PARSER's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace parser {
        class de.fuberlin.wiwiss.d2rq.parser.MapParser {
            {static} + IRI_CHAR_REGEX : String
            - baseURI : String
            {static} - log : Log
            - mapping : Mapping
            - model : OntModel
            {static} - resolver : IRIResolver
            + MapParser()
            {static} + absolutizeURI()
            + parse()
            - copyPrefixes()
            - ensureAllDistinct()
            - ensureIsAbsolute()
            - parseClassMap()
            - parseClassMaps()
            - parseConfiguration()
            - parseDatabase()
            - parseDatabases()
            - parseDownloadMap()
            - parseDownloadMaps()
            - parsePropertyBridge()
            - parsePropertyBridges()
            - parseResourceMap()
            - parseTranslationTable()
            - parseTranslationTables()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace parser {
        class de.fuberlin.wiwiss.d2rq.parser.RelationBuilder {
            - aliases : Set<Alias>
            - condition : Expression
            - database : ConnectedDB
            - isUnique : boolean
            - joinConditions : Set<Join>
            - limit : int
            - limitInverse : int
            - orderSpecs : List<OrderSpec>
            - projections : Set<ProjectionSpec>
            + RelationBuilder()
            + addAlias()
            + addAliased()
            + addAliases()
            + addCondition()
            + addCondition()
            + addJoinCondition()
            + addOther()
            + addProjection()
            + aliases()
            + buildRelation()
            + setIsUnique()
            + setLimit()
            + setLimitInverse()
            + setOrderSpecs()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
