@startuml

title __VTRANSFORMER's Class Diagram__\n

  namespace  {
    class AddAcceptVisitor {
        + AddAcceptVisitor()
        + visit()
    }
  }
  

  namespace  {
    class Main {
        {static} + main()
    }
  }
  

  namespace  {
    class SimpleNode {
        # children : Node[]
        # first : Token
        # id : int
        # last : Token
        # parent : Node
        # parser : JavaParser
        + SimpleNode()
        + SimpleNode()
        + acceptChildren()
        + dump()
        + getFirstToken()
        + getLastToken()
        + jjtAccept()
        + jjtAddChild()
        + jjtClose()
        {static} + jjtCreate()
        + jjtGetChild()
        + jjtGetNumChildren()
        + jjtGetParent()
        + jjtOpen()
        + jjtSetParent()
        + toString()
        + toString()
    }
  }
  

  namespace  {
    class UnparseVisitor {
        # out : PrintStream
        + UnparseVisitor()
        + print()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        + visit()
        # print()
        - addUnicodeEscapes()
    }
  }
  

  SimpleNode .up.|> Node
  UnparseVisitor .up.|> JavaParserVisitor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
