@startuml

title __NODES's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace nodes {
        class de.fuberlin.wiwiss.d2rq.nodes.AllTests {
            {static} + suite()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace nodes {
        class de.fuberlin.wiwiss.d2rq.nodes.NodeMakerTest {
            {static} - table_col1 : Attribute
            {static} - table_col2 : Attribute
            + testBlankNodeMakerToString()
            + testFixedNodeMakerToString()
            + testLanguageLiteralMakerToString()
            + testPlainLiteralMakerToString()
            + testTypedLiteralMakerToString()
            + testURIMakerToString()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace nodes {
        class de.fuberlin.wiwiss.d2rq.nodes.NodeSetTest {
            {static} - alias1foo : Attribute
            {static} - barBlankNodeID : BlankNodeID
            {static} - expression1 : Expression
            {static} - expression2 : Expression
            {static} - fooBlankNodeID : BlankNodeID
            {static} - fooBlankNodeID2 : BlankNodeID
            - nodes : NodeSetConstraintBuilder
            {static} - pattern1 : Pattern
            {static} - pattern1aliased : Pattern
            {static} - pattern2 : Pattern
            {static} - pattern3 : Pattern
            {static} - table1bar : Attribute
            {static} - table1foo : Attribute
            + setUp()
            + testANYNodeDoesNotLimit()
            + testAliasedPatternsNotEmpty()
            + testAttributeAndConstantExpressionIsEquality()
            + testAttributeAndConstantNotEmpty()
            + testBlankNodeAndConstantMatchExpressionIsEquality()
            + testBlankNodeAndConstantMatchNotEmpty()
            + testBlankNodeAndConstantNoMatchEmpty()
            + testBlankNodesFromDifferentClassMapsEmpty()
            + testBlanksAndLiteralsEmpty()
            + testDifferentConstantsEmpty()
            + testDifferentDatatypesEmpty()
            + testDifferentDatatypesFixedEmpty()
            + testDifferentFixedBlanksEmpty()
            + testDifferentFixedLiteralsEmpty()
            + testDifferentFixedURIsEmpty()
            + testDifferentLanguagesEmpty()
            + testDifferentLanguagesFixedEmpty()
            + testDifferentTypeFixedLiteralsEmpty()
            + testEquivalentBlankNodeIDsExpressionIsEquality()
            + testEquivalentPatternsExpressionIsEquality()
            + testExpressionAndConstantExpressionIsEquality()
            + testExpressionAndConstantNotEmpty()
            + testExpressionEqualsAttribute()
            + testExpressionEqualsPattern()
            + testFixedAndConstantEmpty()
            + testFixedAndConstantNotEmpty()
            + testIncompatiblePatternsEmpty()
            + testInitiallyNotEmpty()
            + testLimitToBlankNodes()
            + testLimitToEmptySetIsEmpty()
            + testLimitToFixedNodeNotEmpty()
            + testLimitToLiteralsNotEmpty()
            + testLimitToURIsNotEmpty()
            + testLimitValuesToAttributeNotEmpty()
            + testLimitValuesToBlankNodeIDNotEmpty()
            + testLimitValuesToConstantNotEmpty()
            + testLimitValuesToExpressionNotEmpty()
            + testLimitValuesToPatternNotEmpty()
            + testPatternAndConstantMatchExpressionIsEquality()
            + testPatternAndConstantMatchNotEmpty()
            + testPatternAndConstantNoMatchEmpty()
            + testPatternDifferentColumnFunctionsUnsupported()
            + testPatternEqualsAttribute()
            + testPatternWithColumnFunctionAndColumnUnsupported()
            + testSameAttributeTwiceExpressionIsTrue()
            + testSameAttributeTwiceNotEmpty()
            + testSameBlankNodeIDTwiceExpressionIsTrue()
            + testSameBlankNodeIDTwiceNotEmpty()
            + testSameExpressionTwiceExpressionIsTrue()
            + testSameExpressionTwiceNotEmpty()
            + testSamePatternTwiceExpressionIsTrue()
            + testSamePatternTwiceNotEmpty()
            + testTranslatorUnsupported()
            + testTwoAttributesExpressionIsEquality()
            + testTwoExpressionsTranslatesToEquality()
            + testTwoPatternsExpressionIsConcatEquality()
            + testURIsAndBlanksEmpty()
            + testURIsAndLiteralsEmpty()
            + testVariableNodeDoesNotLimit()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
