@startuml

title __INSTANCEGENERATORS's Class Diagram__\n

  namespace  {
    namespace utoweka {
      namespace instancegenerators {
        class autoweka.instancegenerators.CrossValidation {
            + CrossValidation()
            + CrossValidation()
            + CrossValidation()
            + _getTestingFromParams()
            + _getTrainingFromParams()
            + getAllInstanceStrings()
            # getInstances()
        }
      }
    }
  }
  

  namespace  {
    namespace utoweka {
      namespace instancegenerators {
        class autoweka.instancegenerators.Default {
            + Default()
            + Default()
            + _getTestingFromParams()
            + _getTrainingFromParams()
            + getAllInstanceStrings()
        }
      }
    }
  }
  

  namespace  {
    namespace utoweka {
      namespace instancegenerators {
        class autoweka.instancegenerators.MultiLevel {
            ~ log : Logger
            + MultiLevel()
            + MultiLevel()
            + MultiLevel()
            + _getTestingFromParams()
            + _getTrainingFromParams()
            + getAllInstanceFeatures()
            + getAllInstanceStrings()
            - getInstancesFromParamsForSubClass()
            - setFilterParams()
        }
      }
    }
  }
  

  namespace  {
    namespace utoweka {
      namespace instancegenerators {
        class autoweka.instancegenerators.RandomSubSampling {
            {static} ~ log : Logger
            + RandomSubSampling()
            + RandomSubSampling()
            + RandomSubSampling()
            + _getTestingFromParams()
            + _getTrainingFromParams()
            + getAllInstanceStrings()
            # getInstances()
            # newFilter()
            - setFilterParams()
        }
      }
    }
  }
  

  namespace  {
    namespace utoweka {
      namespace instancegenerators {
        class autoweka.instancegenerators.RandomSubSampling.RegressionResample {
            + createSubsampleWithReplacement()
            + createSubsampleWithoutReplacement()
            + getCapabilities()
            # createSubsample()
        }
      }
    }
  }
  

  autoweka.instancegenerators.RandomSubSampling +-down- autoweka.instancegenerators.RandomSubSampling.RegressionResample


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
