@startuml

title __VOCAB's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace vocab {
        class de.fuberlin.wiwiss.d2rq.vocab.AllTests {
            {static} + suite()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace vocab {
        class de.fuberlin.wiwiss.d2rq.vocab.Test {
            {static} + DummyDatabase : Resource
            {static} + NS : String
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace vocab {
        class de.fuberlin.wiwiss.d2rq.vocab.VocabularySummarizerTest {
            + testAllClassesContainsClass()
            + testAllClassesDoesNotContainProperty()
            + testAllClassesDoesNotContainTermFromOtherNamespace()
            + testAllClassesEmpty()
            + testAllPropertiesContainsProperty()
            + testAllPropertiesDoesNotContainClass()
            + testAllPropertiesDoesNotContainTermFromOtherNamespace()
            + testAllPropertiesEmpty()
            + testFindOneUndefinedClass()
            + testFindOneUndefinedProperty()
            + testFindTwoUndefinedClasses()
            + testFindTwoUndefinedProperties()
            + testGetNamespaceD2RConfig()
            + testGetNamespaceD2RQ()
            + testGetNamespaceEmpty()
            + testNoUndefinedClassesForEmptyModel()
            + testNoUndefinedClassesIfAllClassesDefined()
            + testNoUndefinedClassesIfAllInOtherNamespace()
            + testNoUndefinedClassesWithoutTypeStatement()
            + testNoUndefinedPropertiesForEmptyModel()
            + testNoUndefinedPropertiesIfAllInOtherNamespace()
            + testNoUndefinedPropertiesIfAllPropertiesDefined()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
