@startuml

title __NEGOTIATION's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.pubby.negotiation {
      class de.fuberlin.wiwiss.pubby.negotiation.ContentTypeNegotiator {
          - defaultAcceptRanges : List<MediaRangeSpec>
          - userAgentOverrides : Collection<AcceptHeaderOverride>
          - variantSpecs : List<VariantSpec>
          + addUserAgentOverride()
          + addVariant()
          + getBestMatch()
          + getBestMatch()
          + setDefaultAccept()
          - toAcceptRanges()
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.pubby.negotiation {
      class de.fuberlin.wiwiss.pubby.negotiation.ContentTypeNegotiator.AcceptHeaderOverride {
          - original : String
          - replacement : String
          - userAgentPattern : Pattern
          ~ AcceptHeaderOverride()
          ~ getReplacement()
          ~ matches()
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.pubby.negotiation {
      class de.fuberlin.wiwiss.pubby.negotiation.ContentTypeNegotiator.Negotiation {
          - bestDefaultQuality : double
          - bestDefaultVariant : MediaRangeSpec
          - bestMatchingQuality : double
          - bestMatchingVariant : MediaRangeSpec
          - ranges : List<MediaRangeSpec>
          ~ Negotiation()
          ~ negotiate()
          - evaluateDefaultVariant()
          - evaluateVariant()
          - evaluateVariantAlias()
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.pubby.negotiation {
      class de.fuberlin.wiwiss.pubby.negotiation.ContentTypeNegotiator.VariantSpec {
          - aliases : List<MediaRangeSpec>
          - isDefault : boolean
          - type : MediaRangeSpec
          + VariantSpec()
          + addAliasMediaType()
          + getAliases()
          + getMediaType()
          + isDefault()
          + makeDefault()
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.pubby.negotiation {
      class de.fuberlin.wiwiss.pubby.negotiation.MediaRangeSpec {
          {static} - mediaRangePattern : Pattern
          - mediaType : String
          - parameterNames : List<String>
          {static} - parameterPattern : Pattern
          - parameterValues : List<String>
          {static} - qValuePattern : Pattern
          - quality : double
          - subtype : String
          {static} - tokenPattern : Pattern
          - type : String
          + getBestMatch()
          + getMediaType()
          + getParameter()
          + getParameterNames()
          + getPrecedence()
          + getQuality()
          + getSubtype()
          + getType()
          + isWildcardSubtype()
          + isWildcardType()
          {static} + parseAccept()
          {static} + parseRange()
          {static} + parseType()
          + toString()
          - MediaRangeSpec()
          - buildMediaType()
          {static} - escape()
          {static} - unescape()
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.pubby.negotiation {
      class de.fuberlin.wiwiss.pubby.negotiation.PubbyNegotiator {
          {static} - dataNegotiator : ContentTypeNegotiator
          {static} - pubbyNegotiator : ContentTypeNegotiator
          {static} + getDataNegotiator()
          {static} + getPubbyNegotiator()
      }
    }
  }
  

  de.fuberlin.wiwiss.pubby.negotiation.ContentTypeNegotiator +-down- de.fuberlin.wiwiss.pubby.negotiation.ContentTypeNegotiator.AcceptHeaderOverride
  de.fuberlin.wiwiss.pubby.negotiation.ContentTypeNegotiator +-down- de.fuberlin.wiwiss.pubby.negotiation.ContentTypeNegotiator.Negotiation
  de.fuberlin.wiwiss.pubby.negotiation.ContentTypeNegotiator +-down- de.fuberlin.wiwiss.pubby.negotiation.ContentTypeNegotiator.VariantSpec


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
