@startuml

title __EXPR's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace expr {
        class de.fuberlin.wiwiss.d2rq.expr.AllTests {
            {static} + suite()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace expr {
        class de.fuberlin.wiwiss.d2rq.expr.ConcatenationTest {
            + testCreateEmpty()
            + testCreateOnePart()
            + testFilterEmptyParts()
            + testTwoParts()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace expr {
        class de.fuberlin.wiwiss.d2rq.expr.ConjunctionTest {
            {static} - conjunction12 : Expression
            {static} - conjunction123 : Expression
            {static} - conjunction21 : Expression
            {static} - expr1 : Expression
            {static} - expr2 : Expression
            {static} - expr3 : Expression
            {static} - sql1 : String
            {static} - sql2 : String
            {static} - sql3 : String
            + testCreateConjunction()
            + testEmptyConjunctionIsTrue()
            + testFalseCausesFailure()
            + testFlatten()
            + testOrderDoesNotAffectEquality()
            + testRemoveDuplicates()
            + testSingletonConjunctionIsSelf()
            + testToString()
            + testTrueExpressionsAreSkipped()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace expr {
        class de.fuberlin.wiwiss.d2rq.expr.ExpressionTest {
            - aliases : AliasMap
            + setUp()
            + testConstant()
            + testConstantEquals()
            + testConstantHashCode()
            + testConstantToSQL()
            + testConstantToSQLWithType()
            + testConstantToSQLWithTypeAndAlias()
            + testConstantToString()
            + testConstantTypeAttributeIsRenamed()
            + testFalse()
            + testTrue()
            + testTrueNotEqualFalse()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace expr {
        class de.fuberlin.wiwiss.d2rq.expr.SQLExpressionTest {
            + testCreate()
            + testFindsColumns()
            + testRenameColumnsWithAliasMap()
            + testRenameColumnsWithColumnReplacer()
            + testToString()
            + testTwoExpressionsAreEqual()
            + testTwoExpressionsAreNotEqual()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
