@startuml

title __MAP's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace map {
        class de.fuberlin.wiwiss.d2rq.map.AllTests {
            {static} + suite()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace map {
        class de.fuberlin.wiwiss.d2rq.map.CompileTest {
            - cities : ClassMap
            - citiesNameBridge : PropertyBridge
            - citiesTypeBridge : PropertyBridge
            - countries : ClassMap
            - countriesTypeBridge : PropertyBridge
            - database : Database
            - employees : ClassMap
            - managerBridge : PropertyBridge
            - mapping : Mapping
            - model : Model
            + setUp()
            + testAliasesInRefersToClassMapAreRenamed()
            + testAttributesInRefersToClassMapAreRenamed()
            + testBridgeWithDuplicateClassMapContainsDuplicates()
            + testConditionInRefersToClassMapIsRenamed()
            + testJoinConditionsInRefersToClassMapAreRenamed()
            + testSimpleColumnBridgeContainsNoDuplicates()
            + testSimpleTypeBridgeContainsNoDuplicates()
            - createClassMap()
            - createPropertyBridge()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace map {
        class de.fuberlin.wiwiss.d2rq.map.ConstantValueClassMapTest {
            - collection : ClassMap
            - collectionTypeBridge : PropertyBridge
            - concept : ClassMap
            - conceptTypeBridge : PropertyBridge
            - database : Database
            - mapping : Mapping
            - memberBridge : PropertyBridge
            - model : Model
            + setUp()
            + testValidate()
            - createClassMap()
            - createConstantClassMap()
            - createPropertyBridge()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace map {
        class de.fuberlin.wiwiss.d2rq.map.MappingTest {
            {static} - classMap1 : Resource
            {static} - database1 : Resource
            {static} - database2 : Resource
            + testClassMapReturnsAssignedDatabase()
            + testClassMapWithoutDatabaseCausesValidationError()
            + testMultipleDatabasesForClassMapCauseValidationError()
            + testNewClassMapHasNoDatabase()
            + testNewMappingHasNoClassMaps()
            + testNewMappingWithResource()
            + testNewMappingWithoutResource()
            + testNoDatabaseCausesValidationError()
            + testNoDatabasesInitially()
            + testReturnAddedClassMaps()
            + testReturnAddedDatabase()
            + testReturnResourceFromNewClassMap()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace map {
        class de.fuberlin.wiwiss.d2rq.map.TranslationTableTest {
            ~ table1 : Resource
            + testNewTranslationTableIsEmpty()
            + testNullTranslation()
            + testTranslationTableIsSizeOneAfterAddingOneTranslation()
            + testTranslationTableTranslator()
            + testTranslationsWithDifferentValuesAreNotEqual()
            + testTranslationsWithSameValuesAreEqual()
            + testUndefinedTranslation()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
