@startuml

title __FIND's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace find {
        class de.fuberlin.wiwiss.d2rq.find.FindQuery {
            - context : ExecutionContext
            - limitPerRelation : int
            - triplePattern : Triple
            - tripleRelations : Collection<TripleRelation>
            + FindQuery()
            + FindQuery()
            + iterator()
            - selectedTripleRelations()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace find {
        class de.fuberlin.wiwiss.d2rq.find.TripleQueryIter {
            - wrapped : QueryIter
            + cancel()
            + close()
            {static} + create()
            + hasNext()
            + next()
            - TripleQueryIter()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace find {
        class de.fuberlin.wiwiss.d2rq.find.URIMakerRule {
            - identifierCache : Map<NodeMaker, URIMakerIdentifier>
            + compare()
            + createRuleChecker()
            + sortRDFRelations()
            - priority()
            - uriMakerIdentifier()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace find {
        class de.fuberlin.wiwiss.d2rq.find.URIMakerRule.URIMakerIdentifier {
            - isColumn : boolean
            - isPattern : boolean
            - isURIMaker : boolean
            + limitTo()
            + limitToBlankNodes()
            + limitToEmptySet()
            + limitToLiterals()
            + limitToURIs()
            + limitValues()
            + limitValuesToAttribute()
            + limitValuesToBlankNodeID()
            + limitValuesToExpression()
            + limitValuesToPattern()
            + setUsesTranslator()
            ~ URIMakerIdentifier()
            ~ isURIColumn()
            ~ isURIPattern()
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace find {
        class de.fuberlin.wiwiss.d2rq.find.URIMakerRule.URIMakerRuleChecker {
            - canMatchURIColumn : boolean
            - node : Node
            + URIMakerRuleChecker()
            + addPotentialMatch()
            + canMatch()
        }
      }
    }
  }
  

  de.fuberlin.wiwiss.d2rq.find.URIMakerRule .up.|> Comparator
  de.fuberlin.wiwiss.d2rq.find.URIMakerRule +-down- de.fuberlin.wiwiss.d2rq.find.URIMakerRule.URIMakerIdentifier
  de.fuberlin.wiwiss.d2rq.find.URIMakerRule +-down- de.fuberlin.wiwiss.d2rq.find.URIMakerRule.URIMakerRuleChecker
  de.fuberlin.wiwiss.d2rq.find.URIMakerRule.URIMakerIdentifier .up.|> NodeSetFilter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
