@startuml

title __MAPGEN's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace map {
        namespace en {
          class de.fuberlin.wiwiss.d2rq.mapgen.AllTests {
              {static} + suite()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace map {
        namespace en {
          class de.fuberlin.wiwiss.d2rq.mapgen.FilterParserTest {
              + testCommaInRegex()
              + testComplex()
              + testDotInRegex()
              + testEmpty()
              + testEscapedDotInRegex()
              + testIncompleteRegex()
              + testIncompleteRegexNewline()
              + testMultipleFilters()
              + testMultipleFiltersNewline()
              + testMultipleStrings()
              + testMutlipleRegexFilters()
              + testMutlipleRegexes()
              + testParseAsColumnFilter()
              + testParseAsSchemaFilter()
              + testParseAsSchemaFilterFail()
              + testParseAsSchemaFilterWithRegex()
              + testParseAsTableFilter()
              + testRegex()
              + testRegexWithFlag()
              + testSimple()
              + testTableFilterTooMany()
              - toString()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace map {
        namespace en {
          class de.fuberlin.wiwiss.d2rq.mapgen.IRIEncoderTest {
              + testDontEncodeAlphanumeric()
              + testDontEncodeSafePunctuation()
              + testDontEncodeUnicodeChars()
              + testEncodeASCIIControlChars()
              + testEncodeGenDelims()
              + testEncodeOtherASCIIChars()
              + testEncodePercentSign()
              + testEncodeSubDelims()
              + testEncodeUnicodeControlChars()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
