@startuml

title __EXPR's Class Diagram__\n

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace optimizer {
        namespace expr {
          class de.fuberlin.wiwiss.d2rq.optimizer.expr.AttributeExprEx {
              - nodeMaker : NodeMaker
              + AttributeExprEx()
              + getNodeMaker()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace optimizer {
        namespace expr {
          class de.fuberlin.wiwiss.d2rq.optimizer.expr.ConstantEx {
              - node : Node
              + ConstantEx()
              + ConstantEx()
              + getNode()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace optimizer {
        namespace expr {
          class de.fuberlin.wiwiss.d2rq.optimizer.expr.TransformExprToSQLApplyer {
              {static} - CONSTANT_FALSE : Expression
              {static} - CONSTANT_TRUE : Expression
              - convertable : boolean
              - expression : Stack<Expression>
              {static} - logger : Log
              - nodeRelation : NodeRelation
              - reason : String
              + TransformExprToSQLApplyer()
              {static} + convert()
              + finishVisit()
              + result()
              + startVisit()
              + visit()
              + visit()
              + visit()
              + visit()
              + visit()
              + visit()
              + visit()
              + visit()
              + visit()
              # extensionConvert()
              # extensionSupports()
              {static} ~ cast()
              {static} ~ isSimpleLiteral()
              - conversionFailed()
              - conversionFailed()
              - convert()
              - convert()
              - convertDataType()
              - convertEquality()
              - convertEquals()
              - convertFunction()
              - convertFunction()
              - convertIsBlank()
              - convertIsIRI()
              - convertIsLiteral()
              - convertLang()
              - convertLangMatches()
              - convertLogicalNot()
              - convertNotEquals()
              - convertSameTerm()
              - convertStr()
              - toExpression()
              - visitExprFunction()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace e.fuberlin.wiwiss.d2rq {
      namespace optimizer {
        namespace expr {
          class de.fuberlin.wiwiss.d2rq.optimizer.expr.XSD {
              {static} - decimalType : XSSimpleType
              {static} - doubleType : XSSimpleType
              {static} - floatType : XSSimpleType
              {static} - integerType : XSSimpleType
              {static} + cast()
              {static} + getNumericType()
              {static} + isNumeric()
              {static} + isNumeric()
              {static} + isString()
              {static} + isSupported()
              {static} - getNumericType()
          }
        }
      }
    }
  }
  

  de.fuberlin.wiwiss.d2rq.optimizer.expr.TransformExprToSQLApplyer .up.|> ExprVisitor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
