@startuml

title __TOKENMGRVERSION's Class Diagram__\n

  namespace  {
    class CalcGUI {
        {static} ~ add : Button
        {static} ~ collector : CharCollector
        {static} ~ display : Label
        {static} ~ div : Button
        {static} ~ dot : Button
        {static} ~ eight : Button
        {static} ~ equal : Button
        {static} ~ error : boolean
        {static} ~ firstDigit : boolean
        {static} ~ five : Button
        {static} ~ four : Button
        {static} ~ label : String
        {static} ~ mul : Button
        {static} ~ nine : Button
        {static} ~ one : Button
        {static} ~ quit : Button
        {static} ~ seven : Button
        {static} ~ six : Button
        {static} ~ sub : Button
        {static} ~ three : Button
        {static} ~ two : Button
        {static} ~ zero : Button
        + CalcGUI()
        {static} + Error()
        + handleEvent()
        {static} + print()
        {static} + print()
        {static} ~ getCollector()
    }
  }
  

  namespace  {
    class CharCollector {
        + bufpos : int
        ~ available : int
        ~ bufsize : int
        ~ tokenBegin : int
        - buffer : char[]
        - inBuf : int
        - maxNextCharInd : int
        + BeginToken()
        + CharCollector()
        + CharCollector()
        + Clear()
        + Done()
        + GetImage()
        + GetSuffix()
        + backup()
        + getBeginColumn()
        + getBeginLine()
        + getColumn()
        + getEndColumn()
        + getEndLine()
        + getLine()
        + put()
        + readChar()
        - ExpandBuff()
        - FillBuff()
    }
  }
  

  namespace  {
    class Main {
        {static} + main()
    }
  }
  

  namespace  {
    class MyLexer {
        + MyLexer()
        # LexicalError()
    }
  }
  

  CalcGUI .up.|> CalcInputParserConstants
  CharCollector .up.|> CharStream


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
